-- BestHand capture fixture — auto-generated, safe to delete
return {
  actual_score = 315,
  debuffed_by_blind = false,
  game = {
    blind = {
      disabled = false,
      name = "The Window",
    },
    current_round = {
      ancient_card = {
        suit = "Clubs",
      },
      discards_left = 3,
      dollars = 13,
      hands_left = 1,
      hands_played = 2,
      idol_card = {
        id = 2,
        rank = "2",
        suit = "Hearts",
      },
    },
    deck_remaining = 36,
    dollars = 4,
    hands = {
      ["Five of a Kind"] = {
        chips = 120,
        l_chips = 35,
        l_mult = 3,
        level = 1,
        mult = 12,
        played = 0,
        played_this_round = 0,
        visible = false,
      },
      Flush = {
        chips = 50,
        l_chips = 15,
        l_mult = 2,
        level = 2,
        mult = 6,
        played = 6,
        played_this_round = 1,
        visible = true,
      },
      ["Flush Five"] = {
        chips = 160,
        l_chips = 50,
        l_mult = 3,
        level = 1,
        mult = 16,
        played = 0,
        played_this_round = 0,
        visible = false,
      },
      ["Flush House"] = {
        chips = 140,
        l_chips = 40,
        l_mult = 4,
        level = 1,
        mult = 14,
        played = 0,
        played_this_round = 0,
        visible = false,
      },
      ["Four of a Kind"] = {
        chips = 60,
        l_chips = 30,
        l_mult = 3,
        level = 1,
        mult = 7,
        played = 0,
        played_this_round = 0,
        visible = true,
      },
      ["Full House"] = {
        chips = 40,
        l_chips = 25,
        l_mult = 2,
        level = 1,
        mult = 4,
        played = 0,
        played_this_round = 0,
        visible = true,
      },
      ["High Card"] = {
        chips = 5,
        l_chips = 10,
        l_mult = 1,
        level = 1,
        mult = 1,
        played = 0,
        played_this_round = 0,
        visible = true,
      },
      Pair = {
        chips = 10,
        l_chips = 15,
        l_mult = 1,
        level = 1,
        mult = 2,
        played = 1,
        played_this_round = 1,
        visible = true,
      },
      Straight = {
        chips = 30,
        l_chips = 30,
        l_mult = 3,
        level = 1,
        mult = 4,
        played = 1,
        played_this_round = 0,
        visible = true,
      },
      ["Straight Flush"] = {
        chips = 100,
        l_chips = 40,
        l_mult = 4,
        level = 1,
        mult = 8,
        played = 0,
        played_this_round = 0,
        visible = true,
      },
      ["Three of a Kind"] = {
        chips = 30,
        l_chips = 20,
        l_mult = 2,
        level = 1,
        mult = 3,
        played = 0,
        played_this_round = 0,
        visible = true,
      },
      ["Two Pair"] = {
        chips = 20,
        l_chips = 20,
        l_mult = 1,
        level = 1,
        mult = 2,
        played = 1,
        played_this_round = 0,
        visible = true,
      },
    },
    steel_card_count = 0,
  },
  hand_name = "High Card",
  held = {
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 2,
        nominal = 2,
        suit = "Hearts",
        value = "2",
      },
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 13,
        nominal = 10,
        suit = "Clubs",
        value = "King",
      },
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 12,
        nominal = 10,
        suit = "Clubs",
        value = "Queen",
      },
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 9,
        nominal = 9,
        suit = "Clubs",
        value = "9",
      },
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 5,
        nominal = 5,
        suit = "Clubs",
        value = "5",
      },
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 8,
        nominal = 8,
        suit = "Diamonds",
        value = "8",
      },
      debuff = true,
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 5,
        nominal = 5,
        suit = "Diamonds",
        value = "5",
      },
      debuff = true,
    },
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 4,
        nominal = 4,
        suit = "Diamonds",
        value = "4",
      },
      debuff = true,
    },
  },
  jokers = {
    {
      ability = {
        hands_played_at_create = 2,
        mult = 0,
        name = "Delayed Gratification",
        perma_bonus = 0,
        t_chips = 0,
        t_mult = 0,
        x_mult = 1,
      },
      rarity = 1,
    },
    {
      ability = {
        hands_played_at_create = 2,
        mult = 0,
        name = "Riff-raff",
        perma_bonus = 0,
        t_chips = 0,
        t_mult = 0,
        x_mult = 1,
      },
      rarity = 1,
    },
    {
      ability = {
        hands_played_at_create = 4,
        mult = 0,
        name = "Egg",
        perma_bonus = 0,
        t_chips = 0,
        t_mult = 0,
        x_mult = 1,
      },
      edition = {
        holo = true,
      },
      rarity = 1,
    },
    {
      ability = {
        extra = {
          discard_sub = 1,
          hand_add = 1,
        },
        hands_played_at_create = 7,
        mult = 2,
        name = "Green Joker",
        perma_bonus = 0,
        t_chips = 0,
        t_mult = 0,
        x_mult = 1,
      },
      rarity = 1,
    },
    {
      ability = {
        hands_played_at_create = 7,
        mult = 0,
        name = "Juggler",
        perma_bonus = 0,
        t_chips = 0,
        t_mult = 0,
        x_mult = 1,
      },
      rarity = 1,
    },
  },
  mod_version = "476ea9b",
  played = {
    {
      ability = {
        name = "Default Base",
        perma_bonus = 0,
      },
      base = {
        id = 10,
        nominal = 10,
        suit = "Spades",
        value = "10",
      },
    },
  },
  predicted_score = 210,
}
